services:
  neo4j-load:
    image: neo4j:latest
    container_name: neo4j-load
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./data:/data
    entrypoint: >
      bash -c "neo4j-admin database load neo4j --from-path=/data --verbose"

  neo4j-migrate:
    image: neo4j:latest
    container_name: neo4j-migrate
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./data:/data
    entrypoint: >
      bash -c "neo4j-admin database migrate neo4j"

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: none
      NEO4JLABS_PLUGINS: '["apoc", "graph-data-science"]'
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./ssl:/ssl
    user: "${UID:-1000}:${GID:-1000}"
